CREATE TABLE BOOK_MANAGER(
    Book_No INT PRIMARY KEY AUTO_INCREMENT,
    Book_Name VARCHAR(40) NOT NULL,
    Author VARCHAR(35) NOT NULL,
    Topic VARCHAR(35) NOT NULL,
    Publisher VARCHAR(40) DEFAULT 'Unknown',
    Price DECIMAL(7,2) DEFAULT 0.00,
    Issue_Status VARCHAR(15) DEFAULT 'Not Issued'
);

DESCRIBE BOOK_MANAGER;

CREATE TABLE MEMBER_MANAGER(
    Membership_No INT PRIMARY KEY AUTO_INCREMENT,
    Member_Name VARCHAR(20) NOT NULL,
    Member_MobNo VARCHAR(10) NOT NULL,
    Member_Add VARCHAR(60) NOT NULL,
    Member_EmailId VARCHAR(75) DEFAULT 'NA',
    IdProof_Type VARCHAR(10) NOT NULL,
    IdProof_No VARCHAR(20) NOT NULL UNIQUE,
    Fine_Amt INT DEFAULT 0,
    Membership_Status VARCHAR(10) DEFAULT 'ACTIVE',
    Joining_Date DATE NOT NULL,
    Leave_Date DATE DEFAULT NULL,
    PASSWORD VARCHAR(50),
    IssuedBooks INT DEFAULT 0
);

DESCRIBE MEMBER_MANAGER;

CREATE TABLE TRANSACTION_MANAGER(
    Transaction_Time TIMESTAMP NOT NULL,
    Transaction_No INT PRIMARY KEY AUTO_INCREMENT,
    Book_No INT,
    Membership_No INT,
    Issue_Date DATE,
    Return_Date DATE,
    Transaction_Status INT DEFAULT 1,
    Fine INT Default 0,
    FOREIGN KEY(Book_No) REFERENCES BOOK_MANAGER(Book_No) ON DELETE SET NULL,
    FOREIGN KEY(Membership_No) REFERENCES MEMBER_MANAGER(Membership_No) ON DELETE SET NULL
);

DESCRIBE TRANSACTION_MANAGER;

INSERT INTO BOOK_MANAGER VALUES(101, 'Let Us C', 'Yashavant Kanetkar','C Programming', 'BPB Publication', 399, 'Not Issued');

SELECT * FROM BOOK_MANAGER;
SELECT * FROM TRANSACTION_MANAGER;
SELECT * FROM MEMBER_MANAGER;

INSERT INTO MEMBER_MANAGER VALUES(501, 'SHREYAS', '9370747238', 'Flat No. 2/8, VHB Colony, Ratanlal Plots, Akola', 'japeshreyas@gmail.com' , 'AADHAR','232323', 0, 'ACTIVE', '2022-12-15', NULL, '');
INSERT INTO MEMBER_MANAGER VALUES(500, 'ADMIN', '1111111111', 'H/O', 'admin@librarypython.com', 'ADMIN', '26092001', 0, 'ACTIVE', '1980-01-01', NULL, 'admin@python');

INSERT INTO TRANSACTION_MANAGER VALUES('2022-12-15 17:17:20' ,2001 ,101, 501, '2022-12-16', NULL, 1, 0);

DROP TABLE BOOK_MANAGER;
DROP TABLE MEMBER_MANAGER;
DROP TABLE TRANSACTION_MANAGER;

ALTER TABLE BOOK_MANAGER
MODIFY COLUMN Topic VARCHAR(35) NOT NULL;

ALTER TABLE MEMBER_MANAGER
MODIFY COLUMN PASSWORD VARCHAR(50);

SHOW CREATE TABLE BOOK_MANAGER;
SHOW CREATE TABLE MEMBER_MANAGER;


UPDATE BOOK_MANAGER
SET Book_No=107
WHERE Book_No=108;

ALTER TABLE BOOK_MANAGER AUTO_INCREMENT = 108;

UPDATE MEMBER_MANAGER SET PASSWORD='virajsohli' WHERE Membership_No=503;

ALTER TABLE MEMBER_MANAGER 
ADD COLUMN IssuedBooks INT DEFAULT 0;

SELECT Member_Name
FROM MEMBER_MANAGER
WHERE Member_Name LIKE ('%SHREYAS Jape%');

UPDATE MEMBER_MANAGER
SET IssuedBooks=1, Fine_Amt=70
WHERE Membership_No=503;